In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)


2.6.0+cu124


##Introduction to tensors
###Creating tensors


In [ ]:
scalar = torch.scalar_tensor(100)
scalar.ndim
scalar.item()





100.0

## Vector


In [ ]:
vector = torch.tensor([7,7])
vector.ndim
vector.shape


torch.Size([2])

## Matrix

In [ ]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix.ndim
matrix.shape



torch.Size([2, 2])

# Tensor


In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor.ndim
tensor.shape
tensor[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Randon tensor
## Randor tensor are key to neural network

In [ ]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.4195, 0.7293, 0.5228],
        [0.4767, 0.0664, 0.2858],
        [0.8852, 0.1834, 0.1381]])

In [ ]:
random_tensor.ndim

2

# create tensor of all zeros
# create tensor of all ones

In [ ]:
zeros = torch.zeros(3,3)
zeros

ones = torch.ones(3,4)
ones

tensor1 = torch.rand(3,3)
tensor1

tensor([[0.4531, 0.0598, 0.9865],
        [0.1203, 0.7360, 0.8687],
        [0.2295, 0.8073, 0.9460]])

In [ ]:
torch.arange(start=6,end=30, step=2)

tensor([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### data type is very important
default is float32
some you can use float16, because float16 calculation are faster than float32. some we are can float16 is also called half precision.



## Tensor Operation
#### Multiplication

In [ ]:
tensor2 = random_tensor * tensor1
tensor2

tensor([[0.1901, 0.0436, 0.5157],
        [0.0573, 0.0489, 0.2483],
        [0.2031, 0.1481, 0.1306]])

In [ ]:
tensor2.shape


torch.Size([3, 3])

### tensor
#### 1. datatype
#### 2. Shape
#### 3. device

In [ ]:
tensor = torch.tensor([1,2,3])
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
# matrix multiplication

# dot product or matrix multiplication


tensor4 = torch.tensor([1,2,3])
tensor5 = tensor4 * tensor4
tensor5

torch.matmul(tensor4,tensor4)


tensor(14)

### Matrix multiplication

In [ ]:
tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B = torch.tensor([[7,9],
                         [10,11],
                         [12, 13]])
torch.mm(tensor_A.T,tensor_B)

tensor_A.shape, tensor_A.T.shape, tensor_B.shape
## Matrix rule
## the inner dimensions should match
## the resulting matrix will have shape of outer matrixes dimensions
## 3x2, 2x3 = 3x3
## 4x2, 2x5 = 4x5

(torch.Size([3, 2]), torch.Size([2, 3]), torch.Size([3, 2]))

### min, max, mean, sum etc. tensor aggregation

In [ ]:
x = torch.arange(0,100,10)
x
x.min(), x.max(), x.type(torch.float32).mean(), x.sum()

(tensor(0), tensor(90), tensor(45.), tensor(450))

### positional min and max means which index will have min and max.

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[2],x[4],x[8]

(tensor(20), tensor(40), tensor(80))

# torch stack

### view
### rehshape
### vStack
### squeeze
### unsequeeze
### Permute


In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.tensor([[[1,2,3],[3,4,5],[7,8,9]]])
x


tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [ ]:
x[0][0][2]


tensor(3)

### : is used for all the iteration.

In [ ]:
x[:,:,1]

x[0,0,:]


tensor([1, 2, 3])

## Numpy is popular python numerical computing library


In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

## Reproducibility - taking random out of random.

#### random seed, can be used to lessen the randomness

In [ ]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.8751, 0.1924, 0.4872, 0.7564],
        [0.1713, 0.6618, 0.6501, 0.7109],
        [0.4202, 0.5284, 0.0445, 0.9042]])
tensor([[0.6127, 0.1362, 0.3376, 0.1938],
        [0.2934, 0.6146, 0.2588, 0.3958],
        [0.5921, 0.7082, 0.7917, 0.2600]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42)
random_C = torch.rand(3,4)
torch.manual_seed(42)
random_D = torch.rand(3,4)

print (random_C)
print (random_D)
print (random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and pytouch object on GPUs
### GPU = faster computation


### GCP - Google Computer Platform
### AWS - Amazon
### Azure - Microsoft


In [ ]:
!nvidia-smi


Wed Dec 11 15:33:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"
print (f'{  device  }')

#torch.cuda.device_count()

cuda


### how to use GPU

put tensor and model on GPU

In [ ]:
tensor = torch.tensor([1,2,3]).to(device)
print(tensor, tensor.device)


tensor_back_on_cpu = tensor.cpu().numpy()
print(tensor_back_on_cpu)
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
[1 2 3]
tensor([1, 2, 3], device='cuda:0') cuda:0
